#!/bin/bash
nc -z localhost 8983;
if [ $? -ne 0 ]
then
kill -9 `ps aux | grep searchapp | grep -v grep | awk {'print $2'}`

cd /home/ec2-user/searchApp;nohup java -jar /home/ec2-user/searchApp/start.jar -Djava.util.logging.config.file=etc/logging.properties 1>/dev/null 2>&1 &
fi
nc -z localhost 7686;

if [ $? -ne 0 ]
then
kill -9 `ps aux | grep locationSearchApp | grep -v grep | awk {'print $2'}`
cd /home/ec2-user/locationSearchApp;nohup java -jar /home/ec2-user/locationSearchApp/start.jar -Djava.util.logging.config.file=etc/logging.properties  1>/dev/null 2>&1 &

fi
